/* Auto-generated by scripts/pack-frogger-atlases.py — do not edit. */
export const VIPER_CELL_W = 128
export const VIPER_CELL_H = 160
export const VEHICLE_RECTS = [
  { sx: 38, sy: 7, sw: 84, sh: 73 },
  { sx: 170, sy: 18, sw: 139, sh: 52 },
  { sx: 330, sy: 18, sw: 139, sh: 52 },
  { sx: 490, sy: 19, sw: 139, sh: 50 },
  { sx: 650, sy: 19, sw: 139, sh: 50 },
  { sx: 34, sy: 95, sw: 92, sh: 73 },
  { sx: 170, sy: 99, sw: 139, sh: 66 },
  { sx: 330, sy: 99, sw: 139, sh: 65 },
  { sx: 490, sy: 104, sw: 139, sh: 55 },
  { sx: 650, sy: 104, sw: 139, sh: 56 },
] as const
export const PLATFORM_WIDTHS = [64, 60, 56, 56, 56, 56, 56, 56]
export const PLATFORM_SRC_Y = 4
export const PLATFORM_SRC_H = 64
export const TILE_W = 96
export const TILE_H = 56
export const DEN_W = 112
export const DEN_H = 72
